// ------------------------------------------------------------
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// ------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;
using Dapr;
using Autogenerated = Dapr.Client.Autogen.Grpc;
using FluentAssertions;
using Xunit;
using Microsoft.Extensions.Configuration;
using Dapr.Client;
using Grpc.Net.Client;
using System.Net;

namespace Dapr.Extensions.Configuration.Test
{
    public class DaprSecretStoreConfigurationProviderTest
    {

        [Fact]
        public void LoadSecrets_FromSecretStoreThatReturnsOneValue()
        {
            // Configure Client
            var httpClient = new TestHttpClient()
            {
                Handler = async (entry) =>
                   {
                       var secrets = new Dictionary<string, string>() { { "_default", "secret" } };
                       var secretResponse = new Autogenerated.GetSecretResponseEnvelope();
                       secretResponse.Data.Add(secrets);

                       var streamContent = await GrpcUtils.CreateResponseContent(secretResponse);
                       var response = GrpcUtils.CreateResponse(HttpStatusCode.OK, streamContent);
                       entry.Completion.SetResult(response);
                   }
            };

            Action<DaprClientBuilder> configBuilder = (builder) =>
            {
                builder.UseGrpcChannelOptions(new GrpcChannelOptions { HttpClient = httpClient });
            };

            var config = CreateBuilder()
                    .AddDaprSecretStore("store", new DaprSecretDescriptor[] { new DaprSecretDescriptor("secretName") }, configBuilder)
                    .Build();

            config["secretName"].Should().Be("secret");
        }

        [Fact]
        public void LoadSecrets_FromSecretStoreThatCanReturnsMultipleValues()
        {
            // Configure Client
            var httpClient = new TestHttpClient()
            {
                Handler = async (entry) =>
                   {
                       var secrets = new Dictionary<string, string>() {
                           { "first_secret", "secret1" },
                           { "second_secret", "secret2" }};
                       var secretResponse = new Autogenerated.GetSecretResponseEnvelope();
                       secretResponse.Data.Add(secrets);

                       var streamContent = await GrpcUtils.CreateResponseContent(secretResponse);
                       var response = GrpcUtils.CreateResponse(HttpStatusCode.OK, streamContent);
                       entry.Completion.SetResult(response);
                   }
            };

            Action<DaprClientBuilder> configBuilder = (builder) =>
            {
                builder.UseGrpcChannelOptions(new GrpcChannelOptions { HttpClient = httpClient });
            };

            var config = CreateBuilder()
                    .AddDaprSecretStore("store", new DaprSecretDescriptor[] { new DaprSecretDescriptor("secretName") }, configBuilder)
                    .Build();

            config["first_secret"].Should().Be("secret1");
            config["second_secret"].Should().Be("secret2");
        }

        private IConfigurationBuilder CreateBuilder()
        {
            return new ConfigurationBuilder();
        }
    }
}